//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Api_Demo.Repositories.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opportunity
    {
        public string OpportunityId { get; set; }
        public string OpportunityNm { get; set; }
        public string CountryKey { get; set; }
        public string SalesCaptureDirectorNm { get; set; }
        public string OperatingUnitCd { get; set; }
        public string ROStageCd { get; set; }
        public string MMSStatusCd { get; set; }
        public string OfferingsTxt { get; set; }
        public string ContractExtensionFl { get; set; }
        public string ParentOpportunityId { get; set; }
        public Nullable<System.DateTime> InitGoLiveDt { get; set; }
        public string ServiceGroupNm { get; set; }
        public string SubCSGNm { get; set; }
        public string IndustrySegmentCd { get; set; }
        public string ExpectContractSignQtr { get; set; }
        public Nullable<bool> NewOfferingInd { get; set; }
        public Nullable<bool> ArtificialIntelligenceInd { get; set; }
        public Nullable<bool> CloudInd { get; set; }
        public Nullable<bool> AutomationInd { get; set; }
        public string ROStatusCd { get; set; }
        public string OSReasonCd { get; set; }
        public string CommentTxt { get; set; }
        public Nullable<System.DateTime> TargetDt { get; set; }
        public string CreateUserId { get; set; }
        public System.DateTime CreateDttm { get; set; }
        public string UpdateUserId { get; set; }
        public System.DateTime UpdateDttm { get; set; }
        public string FinancialClientNm { get; set; }
        public string CustomerRelationshipNbr { get; set; }
        public string CustomerRelationshipNm { get; set; }
        public Nullable<System.DateTime> MMSCreatedDateTime { get; set; }
        public Nullable<bool> IsStandardInd { get; set; }
        public string FinancialCustomerNbr { get; set; }
        public Nullable<bool> AllinScopeInd { get; set; }
        public string RRSCommentTxt { get; set; }
        public bool ArchiveInd { get; set; }
    
        public virtual Opportunity Opportunity1 { get; set; }
        public virtual Opportunity Opportunity2 { get; set; }
    }
}
